name: Simple React and Nodejs CI and CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      #Backend
      - name: Install and Test backend
        working-directory: ./server
        run: |
          npm install
          # npm test

      #frontend
      - name: Install and Build frontend
        working-directory: ./client
        run: |
           # Remove existing node_modules in case of cached bad permissions
            rm -rf node_modules package-lock.json
            npm install --unsafe-perm
            npm run build
      - name: CI Finished
        run: echo "CI Pipeline completed Successfully!"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #deploy frontend to Vercel
      - name: Deploy to Vercel
        run: npx vercel --prod --token=$VERCEL_TOKEN --cwd=client
        env: VERCEL_TOKEN:${{secrets.VERCEL_TOKEN}}

      - name: Deploy to Render
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
